quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=Admin2026*
quarkus.datasource.jdbc.url=jdbc:mysql://homeservicesapp.crouecqceg6f.us-east-2.rds.amazonaws.com:3306/home_services_app?useSSL=false&allowPublicKeyRetrieval=true
quarkus.datasource.jdbc.driver=com.mysql.cj.jdbc.Driver


quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

bucket.amazon.s3=homeservicesapp-storage

quarkus.s3.region=us-east-2
quarkus.s3.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=AKIAXIPLKBS7D3POARGC
quarkus.s3.aws.credentials.static-provider.secret-access-key=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

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=home-service-app

smallrye.jwt.sign.key.location=privateKey.pem
