quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=Admin2026*
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/home_services_app

quarkus.http.host=0.0.0.0

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true


mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=home-service-app

smallrye.jwt.sign.key.location=privateKey.pem